// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: absolute_position_proto.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from absolute_position_proto.proto</summary>
public static partial class AbsolutePositionProtoReflection {

  #region Descriptor
  /// <summary>File descriptor for absolute_position_proto.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AbsolutePositionProtoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch1hYnNvbHV0ZV9wb3NpdGlvbl9wcm90by5wcm90byIkChBBYnNvbHV0ZVBv",
          "c2l0aW9uEhAKCHZhbHVlX3B0GAEgASgFYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AbsolutePosition), global::AbsolutePosition.Parser, new[]{ "ValuePt" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class AbsolutePosition : pb::IMessage<AbsolutePosition> {
  private static readonly pb::MessageParser<AbsolutePosition> _parser = new pb::MessageParser<AbsolutePosition>(() => new AbsolutePosition());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<AbsolutePosition> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AbsolutePositionProtoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AbsolutePosition() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AbsolutePosition(AbsolutePosition other) : this() {
    valuePt_ = other.valuePt_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AbsolutePosition Clone() {
    return new AbsolutePosition(this);
  }

  /// <summary>Field number for the "value_pt" field.</summary>
  public const int ValuePtFieldNumber = 1;
  private int valuePt_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ValuePt {
    get { return valuePt_; }
    set {
      valuePt_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as AbsolutePosition);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(AbsolutePosition other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ValuePt != other.ValuePt) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ValuePt != 0) hash ^= ValuePt.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ValuePt != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ValuePt);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ValuePt != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ValuePt);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(AbsolutePosition other) {
    if (other == null) {
      return;
    }
    if (other.ValuePt != 0) {
      ValuePt = other.ValuePt;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          ValuePt = input.ReadInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
