// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_data_proto.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from player_data_proto.proto</summary>
public static partial class PlayerDataProtoReflection {

  #region Descriptor
  /// <summary>File descriptor for player_data_proto.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PlayerDataProtoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdwbGF5ZXJfZGF0YV9wcm90by5wcm90byLtAQoKUGxheWVyRGF0YRIRCglw",
          "bGF5ZXJfaWQYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJEhYKDnBsYXll",
          "cl9pZF9oYXNoGAMgASgFEhcKD3Nob3J0X3BsYXllcl9pZBgEIAEoCRIUCgxm",
          "aXJlYmFzZV91aWQYBSABKAkSDQoFZW1haWwYBiABKAkSEwoLbG9naW5fdG9r",
          "ZW4YByABKAkSFQoNc3RhcnRfcGxheWluZxgIIAEoCRIUCgxsYXN0X3VwZGF0",
          "ZWQYCSABKAkSHgoOcmVwZWF0ZWRfaW5uZXIYCiADKAsyBi5Jbm5lciJ5CgVJ",
          "bm5lchIvCg1tYXBfaW5uZXJtb3N0GAsgAygLMhguSW5uZXIuTWFwSW5uZXJt",
          "b3N0RW50cnkaPwoRTWFwSW5uZXJtb3N0RW50cnkSCwoDa2V5GAEgASgJEhkK",
          "BXZhbHVlGAIgASgLMgouSW5uZXJtb3N0OgI4ASIsCglJbm5lcm1vc3QSDwoH",
          "aW50ZWdlchgBIAEoBRIOCgZzdHJpbmcYAiABKAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayerData), global::PlayerData.Parser, new[]{ "PlayerId", "DisplayName", "PlayerIdHash", "ShortPlayerId", "FirebaseUid", "Email", "LoginToken", "StartPlaying", "LastUpdated", "RepeatedInner" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Inner), global::Inner.Parser, new[]{ "MapInnermost" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
          new pbr::GeneratedClrTypeInfo(typeof(global::Innermost), global::Innermost.Parser, new[]{ "Integer", "String" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class PlayerData : pb::IMessage<PlayerData> {
  private static readonly pb::MessageParser<PlayerData> _parser = new pb::MessageParser<PlayerData>(() => new PlayerData());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PlayerData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PlayerDataProtoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PlayerData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PlayerData(PlayerData other) : this() {
    playerId_ = other.playerId_;
    displayName_ = other.displayName_;
    playerIdHash_ = other.playerIdHash_;
    shortPlayerId_ = other.shortPlayerId_;
    firebaseUid_ = other.firebaseUid_;
    email_ = other.email_;
    loginToken_ = other.loginToken_;
    startPlaying_ = other.startPlaying_;
    lastUpdated_ = other.lastUpdated_;
    repeatedInner_ = other.repeatedInner_.Clone();
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PlayerData Clone() {
    return new PlayerData(this);
  }

  /// <summary>Field number for the "player_id" field.</summary>
  public const int PlayerIdFieldNumber = 1;
  private string playerId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string PlayerId {
    get { return playerId_; }
    set {
      playerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "display_name" field.</summary>
  public const int DisplayNameFieldNumber = 2;
  private string displayName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string DisplayName {
    get { return displayName_; }
    set {
      displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "player_id_hash" field.</summary>
  public const int PlayerIdHashFieldNumber = 3;
  private int playerIdHash_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int PlayerIdHash {
    get { return playerIdHash_; }
    set {
      playerIdHash_ = value;
    }
  }

  /// <summary>Field number for the "short_player_id" field.</summary>
  public const int ShortPlayerIdFieldNumber = 4;
  private string shortPlayerId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ShortPlayerId {
    get { return shortPlayerId_; }
    set {
      shortPlayerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "firebase_uid" field.</summary>
  public const int FirebaseUidFieldNumber = 5;
  private string firebaseUid_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string FirebaseUid {
    get { return firebaseUid_; }
    set {
      firebaseUid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "email" field.</summary>
  public const int EmailFieldNumber = 6;
  private string email_ = "";
  /// <summary>
  ///For auto-login purpose. Do not use for attach online verification.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Email {
    get { return email_; }
    set {
      email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "login_token" field.</summary>
  public const int LoginTokenFieldNumber = 7;
  private string loginToken_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string LoginToken {
    get { return loginToken_; }
    set {
      loginToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "start_playing" field.</summary>
  public const int StartPlayingFieldNumber = 8;
  private string startPlaying_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string StartPlaying {
    get { return startPlaying_; }
    set {
      startPlaying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "last_updated" field.</summary>
  public const int LastUpdatedFieldNumber = 9;
  private string lastUpdated_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string LastUpdated {
    get { return lastUpdated_; }
    set {
      lastUpdated_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "repeated_inner" field.</summary>
  public const int RepeatedInnerFieldNumber = 10;
  private static readonly pb::FieldCodec<global::Inner> _repeated_repeatedInner_codec
      = pb::FieldCodec.ForMessage(82, global::Inner.Parser);
  private readonly pbc::RepeatedField<global::Inner> repeatedInner_ = new pbc::RepeatedField<global::Inner>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::Inner> RepeatedInner {
    get { return repeatedInner_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PlayerData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PlayerData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PlayerId != other.PlayerId) return false;
    if (DisplayName != other.DisplayName) return false;
    if (PlayerIdHash != other.PlayerIdHash) return false;
    if (ShortPlayerId != other.ShortPlayerId) return false;
    if (FirebaseUid != other.FirebaseUid) return false;
    if (Email != other.Email) return false;
    if (LoginToken != other.LoginToken) return false;
    if (StartPlaying != other.StartPlaying) return false;
    if (LastUpdated != other.LastUpdated) return false;
    if(!repeatedInner_.Equals(other.repeatedInner_)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
    if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
    if (PlayerIdHash != 0) hash ^= PlayerIdHash.GetHashCode();
    if (ShortPlayerId.Length != 0) hash ^= ShortPlayerId.GetHashCode();
    if (FirebaseUid.Length != 0) hash ^= FirebaseUid.GetHashCode();
    if (Email.Length != 0) hash ^= Email.GetHashCode();
    if (LoginToken.Length != 0) hash ^= LoginToken.GetHashCode();
    if (StartPlaying.Length != 0) hash ^= StartPlaying.GetHashCode();
    if (LastUpdated.Length != 0) hash ^= LastUpdated.GetHashCode();
    hash ^= repeatedInner_.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (PlayerId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(PlayerId);
    }
    if (DisplayName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(DisplayName);
    }
    if (PlayerIdHash != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PlayerIdHash);
    }
    if (ShortPlayerId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(ShortPlayerId);
    }
    if (FirebaseUid.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(FirebaseUid);
    }
    if (Email.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Email);
    }
    if (LoginToken.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(LoginToken);
    }
    if (StartPlaying.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(StartPlaying);
    }
    if (LastUpdated.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(LastUpdated);
    }
    repeatedInner_.WriteTo(output, _repeated_repeatedInner_codec);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (PlayerId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerId);
    }
    if (DisplayName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
    }
    if (PlayerIdHash != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerIdHash);
    }
    if (ShortPlayerId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ShortPlayerId);
    }
    if (FirebaseUid.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FirebaseUid);
    }
    if (Email.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
    }
    if (LoginToken.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginToken);
    }
    if (StartPlaying.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(StartPlaying);
    }
    if (LastUpdated.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(LastUpdated);
    }
    size += repeatedInner_.CalculateSize(_repeated_repeatedInner_codec);
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PlayerData other) {
    if (other == null) {
      return;
    }
    if (other.PlayerId.Length != 0) {
      PlayerId = other.PlayerId;
    }
    if (other.DisplayName.Length != 0) {
      DisplayName = other.DisplayName;
    }
    if (other.PlayerIdHash != 0) {
      PlayerIdHash = other.PlayerIdHash;
    }
    if (other.ShortPlayerId.Length != 0) {
      ShortPlayerId = other.ShortPlayerId;
    }
    if (other.FirebaseUid.Length != 0) {
      FirebaseUid = other.FirebaseUid;
    }
    if (other.Email.Length != 0) {
      Email = other.Email;
    }
    if (other.LoginToken.Length != 0) {
      LoginToken = other.LoginToken;
    }
    if (other.StartPlaying.Length != 0) {
      StartPlaying = other.StartPlaying;
    }
    if (other.LastUpdated.Length != 0) {
      LastUpdated = other.LastUpdated;
    }
    repeatedInner_.Add(other.repeatedInner_);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          PlayerId = input.ReadString();
          break;
        }
        case 18: {
          DisplayName = input.ReadString();
          break;
        }
        case 24: {
          PlayerIdHash = input.ReadInt32();
          break;
        }
        case 34: {
          ShortPlayerId = input.ReadString();
          break;
        }
        case 42: {
          FirebaseUid = input.ReadString();
          break;
        }
        case 50: {
          Email = input.ReadString();
          break;
        }
        case 58: {
          LoginToken = input.ReadString();
          break;
        }
        case 66: {
          StartPlaying = input.ReadString();
          break;
        }
        case 74: {
          LastUpdated = input.ReadString();
          break;
        }
        case 82: {
          repeatedInner_.AddEntriesFrom(input, _repeated_repeatedInner_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class Inner : pb::IMessage<Inner> {
  private static readonly pb::MessageParser<Inner> _parser = new pb::MessageParser<Inner>(() => new Inner());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Inner> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PlayerDataProtoReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Inner() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Inner(Inner other) : this() {
    mapInnermost_ = other.mapInnermost_.Clone();
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Inner Clone() {
    return new Inner(this);
  }

  /// <summary>Field number for the "map_innermost" field.</summary>
  public const int MapInnermostFieldNumber = 11;
  private static readonly pbc::MapField<string, global::Innermost>.Codec _map_mapInnermost_codec
      = new pbc::MapField<string, global::Innermost>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::Innermost.Parser), 90);
  private readonly pbc::MapField<string, global::Innermost> mapInnermost_ = new pbc::MapField<string, global::Innermost>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::MapField<string, global::Innermost> MapInnermost {
    get { return mapInnermost_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Inner);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Inner other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!MapInnermost.Equals(other.MapInnermost)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= MapInnermost.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    mapInnermost_.WriteTo(output, _map_mapInnermost_codec);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += mapInnermost_.CalculateSize(_map_mapInnermost_codec);
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Inner other) {
    if (other == null) {
      return;
    }
    mapInnermost_.Add(other.mapInnermost_);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 90: {
          mapInnermost_.AddEntriesFrom(input, _map_mapInnermost_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class Innermost : pb::IMessage<Innermost> {
  private static readonly pb::MessageParser<Innermost> _parser = new pb::MessageParser<Innermost>(() => new Innermost());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Innermost> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PlayerDataProtoReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Innermost() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Innermost(Innermost other) : this() {
    integer_ = other.integer_;
    string_ = other.string_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Innermost Clone() {
    return new Innermost(this);
  }

  /// <summary>Field number for the "integer" field.</summary>
  public const int IntegerFieldNumber = 1;
  private int integer_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Integer {
    get { return integer_; }
    set {
      integer_ = value;
    }
  }

  /// <summary>Field number for the "string" field.</summary>
  public const int StringFieldNumber = 2;
  private string string_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string String {
    get { return string_; }
    set {
      string_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Innermost);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Innermost other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Integer != other.Integer) return false;
    if (String != other.String) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Integer != 0) hash ^= Integer.GetHashCode();
    if (String.Length != 0) hash ^= String.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Integer != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Integer);
    }
    if (String.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(String);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Integer != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Integer);
    }
    if (String.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(String);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Innermost other) {
    if (other == null) {
      return;
    }
    if (other.Integer != 0) {
      Integer = other.Integer;
    }
    if (other.String.Length != 0) {
      String = other.String;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          Integer = input.ReadInt32();
          break;
        }
        case 18: {
          String = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
